### ISSUE TITLE
Implement idea w/pics and attachments

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#13] opened 2016-06-17 15:55 UTC
https://docs.google.com/presentation/d/1bMFnUz_5PilDtymvq9SYAc03AAKYebT0dMIBfzJDV8I/edit#slide=id.g1195d59c95_0_0

https://docs.google.com/drawings/d/1H_6HyAAHLPzesKpY80fPfk1YMrB9iobdYmKs2nqaNNI/edit

**Comment by Hallm13** [comment] 2016-06-17 16:28
Include read more box with links

**Comment by siruguri** [comment] 2016-07-05 22:24
#6 has some other details; but it's closed as duplicate of this.

**Closed** 2016-08-19 15:17 UTC
Labels: enhancement
